branch-defaults:
  master:
    environment: CustumiseApi-env
environment-defaults:
  CustumiseApi-env:
    branch: null
    repository: null
global:
  application_name: amidos-custumise
  default_ec2_keyname: amidos-custumise
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
