# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06e289dee8ed783634472aa777915d435009c19c0bf3587bd70d26978590ac0e1d7c22ab139a0e6b481c4c930aa6ba12419e39c4b4eecd690f571952079fccf5
  jwt_auth_secret: d9f3e297501f58da6f83b833568cfbe0e5602050fcaa4bca9b80742dbac0b6637b59ddd4b1bf58a7c5709ebd140cd6deadd4419566e9233af7441134902b3a41
  facebook_key: 1377693188950907
  facebook_secret: cc065580fc9cf30dc039366934e68518
  goole_api_key: AIzaSyDpHnrdNO7qbuKPnTsRkfUCjPEp3JD18Ec
  google_client_id: 323886467053-tl90536bohsjtr71t10v1887t01egbm8.apps.googleusercontent.com
  google_client_secret: uRyyATKR4rkSzdukKNdCjscO
  twilio_sid: AC8425b700b9f0b568f21391f9dd145db6
  twilio_token: 981d49fa6a25fbcb1cb07acfb2da25f2
  msg91_auth_key: 169953AnNBKIaj93n5991ed05
  s3_bucket_name: amidos-custumise
  aws_access_key_id: AKIAJUO657TYD6D2AQJQ
  aws_secret_access_key: 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
  aws_region: ap-south-1
  #store_url: http://192.168.0.103:3090/

production:
  s3_bucket_name: amidos-custumise
  aws_access_key_id: AKIAJUO657TYD6D2AQJQ
  aws_secret_access_key: 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
  aws_region: ap-south-1

test:
  secret_key_base: fd361bb4b7ed56030729b74385366842c91557ded61711895f1a6981213e62d5076944b8e0240d01c803d3842700beddfbeecd866854ce277bde506497661857
  jwt_auth_secret: 758b7d9f6d81ad8cc24607887ecfa8d89a414e20dc0d58aec42026649faf4536fb5324290fa502fd7bae9cbc1a50213a66b5fa839e5337b67841eead8ae2a49d
  facebook_key: 1377693188950907
  facebook_secret: cc065580fc9cf30dc039366934e68518
  goole_api_key: AIzaSyDpHnrdNO7qbuKPnTsRkfUCjPEp3JD18Ec
  google_client_id: 323886467053-tl90536bohsjtr71t10v1887t01egbm8.apps.googleusercontent.com
  google_client_secret: uRyyATKR4rkSzdukKNdCjscO
  twilio_sid: asdasd
  twilio_token: assad
  msg91_auth_key: asdds
  #store_url: http://192.168.0.103:3090/